project_id = "hjlmhuboqunwplieenwb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.garmin-sync]
verify_jwt = true

[functions.garmin-auto-sync]
verify_jwt = false

[auth]
enabled = true
port = 54328